site_name: Tom's Blog

theme:
    name: null
    custom_dir: 'theme/'

markdown_extensions:
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg        

nav:
    # - 'presenting-analytics-researching-vs-lawyering.md'
    # - 'what-is-an-analytics-engineer.md'
    - 'data-lakes-vs-data-warehouses.md'
    - 'dim-and-fact-tables.md'
    - 'github-codespaces.md'    